### ISSUE TITLE
NoBackSpace-Issue-1

### ISSUE THREAD

**Issue by NoBackSpace** [oroszl/statfiz-gyak#5]
A következő hibákat találtam:

01-Hasznos_matematikai_formulak.lyx : 
1, "Vissza írva..." -> "Visszaírva..."
2, "...meg hát hogy hogyan..." -> "...meg hát, hogy hogyan..."
3, "(sorrendtől függően
\begin_inset Formula $\pm\mathrm{i}$
\end_inset

 faktorral):" -> itt hiányzik egy "space" a "\pm\mathrm{i}" előtt.

03-Kanonikus_sokasag.lyx :
4, 388-as képlet: egyszerre van egyenlőség és approx is.
5, 388-as képlet: az utolsó átalakításnál a plusz helyett mínusz kell. Ez a hiba folytatódik később is, és megjelenik a 392-es képletben is.

Solymos Adrián

**Comment by oroszl** [comment]
kössz az észrevételeket.. emlékeztem is hogy a perturbációnál volt egy előjel.. :+1: 
upgrade-eltem a dolgokat és be is írlak a táblázatba is..
