### ISSUE TITLE
Néhány hiba jelzése2

### ISSUE THREAD

**Issue by NoBackSpace** [oroszl/statfiz-gyak#7]
Lehetséges, hogy néhány hiba nem is hiba és én néztem el. De azért itt vannak a megjegyzéseim:

1, 503-as egyenlet: <N> kellen nem? Nagykanonikusan dolgozunk nem? Ezt érdemes lenne jelezni.

2, 46.o.: "d/nü -> d/nü+1helyettesítést": hiányzó space.

3, 508, 509-es képletek: ":d" hiányzó space. 

4, 47.o.: "határozzuk meg most a fenn tárgyalt": szerintem fent tárgyalt. (legalábbis a "fenn tárgyalt" változatot még nem hallottam)

5, 47.o.: "... kapjuk hogy": hiányzó vessző.

6, 508,509-es képletek: hiányzik az <N>.

7, 524-es képlet: "hbar" helyett "h" kell.

8, 50.o.: "Ferm-igázban".

9, 568-as képlet második sor második tagban 2-es helyett 8-as kell.

10, 52.o.: Az órán már valamennyire kifejtettem, hogy mennyire furcsának találom azt amit itt csinálunk. Ha feltesszük, hogy N fix (ami nekem már alapból furcsa mert úgy tűnt, hogy nagykanonikus soksasággal dolgoztunk...) akkor valamit változtatni kell a jelöléseken mert valami nagyon nincs rendben:
- 565-ben mü_0-ig integrálunk nemde?
- 567-ben hasonlóan
- 568-ban először végtelenig integrálunk

11, 55.o.: "pozotív"

12, 55.o.: "hogyGamma(-1/2)" hiányzó space

Solymos Adrián

**Comment by oroszl** [comment]
bevittem a javaslatokat
