### ISSUE TITLE
Hibajelzések - nb

### ISSUE THREAD

**Issue by balintnegyesi** [oroszl/statfiz-gyak#8]
Néhány inkább megjegyzés, mint hiba és a többség csak elütés:

1) 8. oldal -- (66) egyenlet után inkább "az utolsó esetében az egyenlőség ..."
2) 11. oldal -- 5. alfejezet címben: "... egydimenziós részecske"
3) 14. oldal -- (129) után "... visszakapjuk..."
4) 16. oldal -- (165) előtt közvetlen ".. értelemszerűen"
5) 17. oldal -- alul (180) és (181) közt: "...$m=\pm{}1$ esetén tart $\mp{}\infty$-hez..." előjelhelyesen a határértékek.
6) 19. oldal -- (200) és (201) közt: "... vegyük észre..." (elütés)
7) 19. oldal -- 14. ábra jelmagyarázat --> szerintem az első golyó előtti 'fal' nem számít és nem két fekete golyóval kellene kezdődnie a szekvenciának.
8) 20. oldal -- 10. alfejezet végig: N eddig szabadsági fokot jelölt, itt meg változószámot. Talán következetesebb lenne itt valami más jelölés.
9) 23. oldal -- (247) után: "...ugyanazt..."
10) 24. oldal -- (259) és (260) közt: "...egyes..."
11) 25. oldal -- teteje: "... két legalsó energiaszintet..."
12) 25. oldal -- (265) és (266) közt: "...ugyanazt..."
13) 29. oldal -- (321)-ben a harmadik egyenlőség után szerintem hibás egy előjel. Helyesen: "...=\frac{2}{\beta}-\mathcal{E}d\frac{\cosh \beta\mathcal{E}d}{\sinh\beta\mathcal{E}d}=..."
14) 30. oldal -- (328) előtt: "...állapotösszeg..."
15) 30. oldal -- (328) és (329) között: így is érthető, de talán helyesebb így: "Vegyük észre, hogy ez egy mértani sorozat első $(2j+1)$ tagjának összege". Így nem vezet félre a végtelen mértani sorrral.
16) 30. oldal -- (330) előtt: "...energiaskála..."
17) 30. oldal -- (331) előtt: "...szabadenergia..."
18) 33. oldal -- (365) után: szerintem inkább egyben "...átlagenergia..."
19) 35. oldal -- (382) és (383) között: "...szabadenergia..."
20) 36. oldal -- (401) előtt és után: így kicsit összefüggéstelen, inkább "A hengerrel együtt forgó koordináta-rendszerben ez az L... kifejezésre módosul"
21) 37. oldal -- teteje "...A Hamilton-függvényt..."
22) 38. oldal -- (423) és (424) között: "...sűrűségeloszlás..."
23) 38. oldal -- (424) után: "Összevetve..."
24) 38. oldal -- 23. alfejezet alatti bekezdés: "...gázrészecskék..."
25) 55. oldal -- (598)-ban "...pozitív..."
26) 55. oldal -- (598) utáni bekezdés: "...részecskeszáma..."

**Comment by oroszl** [comment]
átvéve
